[package]
name = "kml_inner_boundary_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
kml = "0.8.4"

[dependencies.kml_proposed]
package = "kml"
git = "https://github.com/cfzimmerman/kml.git"
branch = "support-multi-innerBoundaryIs"
